### ISSUE TITLE
IncompatibleClassChangeError during start of HelloWorldTestApplication 

### ISSUE THREAD

**Issue by austermann** [copper-engine/copper-starter#5]
`2017.04.18 16:33:56,722 INFO  [main] org.copperengine.core.tranzient.TransientScottyEngine [] - Engine is starting up...
Exception in thread "main" java.lang.IncompatibleClassChangeError: class org.copperengine.core.instrument.ScottyFindInterruptableMethodsVisitor has interface org.objectweb.asm.ClassVisitor as super class
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
       at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       at org.copperengine.core.wfrepo.FileBasedWorkflowRepository.findInterruptableMethods(FileBasedWorkflowRepository.java:422)
       at org.copperengine.core.wfrepo.FileBasedWorkflowRepository.createWfClassMap(FileBasedWorkflowRepository.java:312)
       at org.copperengine.core.wfrepo.FileBasedWorkflowRepository.start(FileBasedWorkflowRepository.java:253)
       at org.copperengine.core.tranzient.TransientScottyEngine.startup(TransientScottyEngine.java:231)
       at org.copperengine.examples.simple.TransientEngineFactory.create(TransientEngineFactory.java:108)
       at org.copperengine.examples.simple.HelloWorldTestApplication.run(HelloWorldTestApplication.java:50)
       at org.copperengine.examples.simple.HelloWorldTestApplication.main(HelloWorldTestApplication.java:36)`

**Comment by austermann** [comment]
Same problem as described here
https://groups.google.com/forum/#!searchin/copper-engine/IncompatibleClassChangeError%7Csort:relevance/copper-engine/z-5mUZheS9g/34bKakH0PEAJ
